source('https://rubygems.org')

gem('sinatra')
gem('sinatra-contrib')
gem('rspec')
gem('capybara')
gem('pry')
gem('launchy')
gem('pg')
gem('sinatra-activerecord')
gem('rake')
gem("shoulda-matchers", '~> 2.0')
gem('warden')
gem('bcrypt-ruby')
gem 'sinatra-flash', '0.3.0', require: 'sinatra/flash'
